/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Models.AttributesTableModel;
import GUI.Models.MyTagsTreeNode;
import GUI.Models.TagsTableModel;
import GUI.Models.TextContentTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import xmlgenerator.SubTree;
import xmlgenerator.XMLGenerator;

/**
 *
 * @author Anatoly
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        depthMinField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        depthMaxField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        branchMinField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        branchMaxField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        attributeMaxField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        attributeMinField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        saveButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        copyButton = new javax.swing.JButton();
        cutButton = new javax.swing.JButton();
        pasteButton = new javax.swing.JButton();
        removeSubTreeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedNodeTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        imperativeAttributesTable = new javax.swing.JTable();
        attrPlusButton = new javax.swing.JButton();
        attrMinusButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        imperativeTagsTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        tagMinusButton = new javax.swing.JButton();
        tagPlusButton = new javax.swing.JButton();
        removeTagButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textContentTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        contentMinusButton = new javax.swing.JButton();
        contentPlusButton = new javax.swing.JButton();
        maximalDepthFileld = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("XML Generator");

        jLabel2.setText("Глубина случайных тегов:");

        jLabel4.setText("–");

        jButton1.setText("Сгенерировать!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Кол-во случайных тегов на уровень:");

        branchMinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchMinFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("–");

        jLabel6.setText("Количество случайных атрибутов:");

        jLabel7.setText("–");

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        saveButton.setText("Сохранить!");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Название:");

        copyButton.setText("Копировать");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        cutButton.setText("Вырезать");
        cutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutButtonActionPerformed(evt);
            }
        });

        pasteButton.setText("Вставить");
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });

        removeSubTreeButton.setText("Поддерево");
        removeSubTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubTreeButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(selectedNodeTextPane);

        imperativeAttributesTable.setModel(myAtrributeTableModel);
        jScrollPane3.setViewportView(imperativeAttributesTable);

        attrPlusButton.setText("+");
        attrPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrPlusButtonActionPerformed(evt);
            }
        });

        attrMinusButton.setText("-");
        attrMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrMinusButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Обязательные атрибуты:");

        imperativeTagsTable.setModel(myTagsTableModel);
        jScrollPane4.setViewportView(imperativeTagsTable);

        jLabel10.setText("Обязательные теги:");

        tagMinusButton.setText("-");
        tagMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagMinusButtonActionPerformed(evt);
            }
        });

        tagPlusButton.setText("+");
        tagPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagPlusButtonActionPerformed(evt);
            }
        });

        removeTagButton.setText("Тег");
        removeTagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTagButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Удалить:");

        textContentTable.setModel(myTextContentTableModel);
        jScrollPane5.setViewportView(textContentTable);

        jLabel12.setText("Содержимое:");

        jScrollPane6.setViewportView(jTree2);

        contentMinusButton.setText("-");
        contentMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMinusButtonActionPerformed(evt);
            }
        });

        contentPlusButton.setText("+");
        contentPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentPlusButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Максимальная глубина:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removeSubTreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removeTagButton)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(copyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(pasteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 133, Short.MAX_VALUE)
                                                .addComponent(contentPlusButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contentMinusButton))
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(tagPlusButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tagMinusButton))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(0, 96, Short.MAX_VALUE))
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(attrPlusButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(attrMinusButton))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 49, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(depthMinField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(depthMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(branchMinField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(branchMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(attributeMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel7))
                                                    .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(maximalDepthFileld, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                                    .addComponent(attributeMinField)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(removeSubTreeButton)
                                    .addComponent(removeTagButton)
                                    .addComponent(jLabel11))
                                .addGap(7, 7, 7)
                                .addComponent(copyButton))
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(depthMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(depthMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(branchMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(branchMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(attributeMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attributeMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maximalDepthFileld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attrMinusButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(attrPlusButton)
                                .addComponent(tagMinusButton)
                                .addComponent(tagPlusButton)
                                .addComponent(contentMinusButton)
                                .addComponent(contentPlusButton)))
                        .addGap(54, 54, 54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchMinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchMinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchMinFieldActionPerformed

    private boolean inputIsCorrect(){
        
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!inputIsCorrect()){
            ErrorDialog errDialog = new ErrorDialog(this, true);
            errDialog.setVisible(true);
            return;
        }
        int maxDepth, minDepth, branchMax, branchMin, attrMax, attrMin, globalMaxDepth;
        try{minDepth = Integer.valueOf( depthMinField.getText().trim());}
        catch(NumberFormatException exc){ minDepth = 0;}
        try{maxDepth = Integer.valueOf( depthMaxField.getText().trim());}
        catch(NumberFormatException exc){ maxDepth = minDepth;}
        try{branchMin = Integer.valueOf( branchMinField.getText().trim());}
        catch(NumberFormatException exc){ branchMin = 0;}
        try{branchMax = Integer.valueOf( branchMaxField.getText().trim());}
        catch(NumberFormatException exc){ branchMax = branchMin;}
        try{attrMin = Integer.valueOf(attributeMinField.getText().trim());}
        catch(NumberFormatException exc){ attrMin = 0;}
        try{attrMax = Integer.valueOf( attributeMaxField.getText().trim());}
        catch(NumberFormatException exc){ attrMax = attrMin;}
        try{globalMaxDepth = Integer.valueOf( maximalDepthFileld.getText().trim());}
        catch(NumberFormatException exc){globalMaxDepth = Integer.MAX_VALUE;}
        String rootName = nameTextField.getText();
        HashMap<Integer,HashMap<String, String>> attributesInLevel = new HashMap<>();
        HashMap<String, HashMap<String, String>> attributesOfTags = new HashMap<>();
        HashMap<String, String> attributesInAllLevels = new HashMap<>();
        for (int i = 0; i < imperativeAttributesTable.getRowCount(); i++){
            String attrName = (String) imperativeAttributesTable.getValueAt(i, 0);
            String attrValue = (String) imperativeAttributesTable.getValueAt(i, 1);
            String levelsAndtags = (String) imperativeAttributesTable.getValueAt(i, 2);
            if (levelsAndtags.equals("all") || levelsAndtags.trim().equals(""))
                attributesInAllLevels.put(attrName, attrValue);
            else{
                String[] levelsIntervalsAndPoints = levelsAndtags.split(",");
                ArrayList<Integer> levelsArray = XMLGenerator.getIntegers(levelsIntervalsAndPoints);
                ArrayList<String> tagsArray = XMLGenerator.getTagsInLastGetIntegerCalling();
                for (Integer lvl: levelsArray){
                    HashMap<String, String> attrInThisLevel;
                    if (attributesInLevel.containsKey(lvl))
                        attrInThisLevel = attributesInLevel.get(lvl);
                    else{
                        attrInThisLevel = new HashMap<>();
                        attributesInLevel.put(lvl, attrInThisLevel);
                    }
                    attrInThisLevel.put(attrName, attrValue);
                }
                for (String tag: tagsArray){
                    HashMap<String, String> attrOfThisTag;
                    if (attributesOfTags.containsKey(tag))
                        attrOfThisTag = attributesOfTags.get(tag);
                    else{
                        attrOfThisTag = new HashMap<>();
                        attributesOfTags.put(tag, attrOfThisTag);
                    }
                    attrOfThisTag.put(attrName, attrValue);
                }
            }
        }
        HashMap<Integer, HashMap<String, String[]>> tagsInLevels = new HashMap<>();
        HashMap<String, HashMap<String, String[]>> tagsofParentTags = new HashMap<>();
        HashMap<String, String[]> tagsInAllLevels = new HashMap<>();
        for (int i = 0; i < imperativeTagsTable.getRowCount(); i++){
            String tagName = (String) imperativeTagsTable.getValueAt(i, 0);
            String amountInLevelStr = (String) imperativeTagsTable.getValueAt(i, 1);
            String[] amountArray = amountInLevelStr.split(",");
            String levelsAndTagsStr = (String) imperativeTagsTable.getValueAt(i, 2);
            if (levelsAndTagsStr.equals("all") || levelsAndTagsStr.trim().equals(""))
                tagsInAllLevels.put(tagName,amountArray);
            else{
                String[] levelsArray = levelsAndTagsStr.split(",");
                ArrayList<Integer> levelsOfTag = XMLGenerator.getIntegers(levelsArray);
                ArrayList<String> parentTagsOfTag = XMLGenerator.getTagsInLastGetIntegerCalling();
                for (Integer lvl: levelsOfTag){
                    HashMap<String, String[]> tagsInThisLevel;
                    if (tagsInLevels.containsKey(lvl))
                        tagsInThisLevel = tagsInLevels.get(lvl);
                    else{
                        tagsInThisLevel = new HashMap<>();
                        tagsInLevels.put(lvl, tagsInThisLevel);
                    }
                    tagsInThisLevel.put(tagName, amountArray);
                }
                for (String tag: parentTagsOfTag){
                    HashMap<String, String[]> tagsOfThisParentTag;
                    if (tagsofParentTags.containsKey(tag))
                        tagsOfThisParentTag = tagsofParentTags.get(tag);
                    else{
                        tagsOfThisParentTag = new HashMap<>();
                        tagsofParentTags.put(tag, tagsOfThisParentTag);
                    }
                    tagsOfThisParentTag.put(tagName, amountArray);
                }
            }
        }
        HashMap<Integer, ArrayList<String>> textContentInLevels = new HashMap<>();
        HashMap<String, ArrayList<String>> textContentInTags = new HashMap<>();
        ArrayList<String> textContentInAllLevels = new ArrayList<>();
        for (int i = 0; i < textContentTable.getRowCount(); i++){
            String levelsOrTagsStr = (String) textContentTable.getValueAt(i, 0);
            String textContent = (String) textContentTable.getValueAt(i, 1);
            if (levelsOrTagsStr.equals("all") || levelsOrTagsStr.trim().equals(""))
                textContentInAllLevels.add(textContent);
            else{
                String[] levelsAndTagsArray = levelsOrTagsStr.split(",");
                ArrayList<Integer> levelsOfTextContent = XMLGenerator.getIntegers(levelsAndTagsArray);
                ArrayList<String> tagsOfTextContent = XMLGenerator.getTagsInLastGetIntegerCalling();
                for (Integer lvl: levelsOfTextContent){
                    ArrayList<String> textContentOfThisLevel;
                    if (textContentInLevels.containsKey(lvl))
                        textContentOfThisLevel = textContentInLevels.get(lvl);
                    else{
                        textContentOfThisLevel = new ArrayList<>();
                        textContentInLevels.put(lvl, textContentOfThisLevel);
                    }
                    textContentOfThisLevel.add(textContent);
                }
                for (String tag: tagsOfTextContent){
                    ArrayList<String> textContentOfThisTag;
                    if (textContentInTags.containsKey(tag))
                        textContentOfThisTag = textContentInTags.get(tag);
                    else{
                        textContentOfThisTag = new ArrayList<>();
                        textContentInTags.put(tag, textContentOfThisTag);
                    }
                    textContentOfThisTag.add(textContent);
                }
            }
        }
        SubTree xmlTree = new SubTree(rootName);
        xmlTree.setGlobalMaximunDepth(globalMaxDepth);
        xmlTree.fill(minDepth, maxDepth, branchMin, branchMax);
        xmlTree.setImperativeTags(tagsInLevels, tagsInAllLevels, tagsofParentTags);
        xmlTree.setIncidentalAttributes(attrMax, attrMin);
        xmlTree.setImperativeAttributes(attributesInLevel, attributesInAllLevels, attributesOfTags);
        xmlTree.setTextContent(textContentInLevels, textContentInAllLevels, textContentInTags);
        root.addChild(xmlTree);
        updateTree();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void removeSubTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubTreeButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree remNode = TC.getAssociatedNode();
        if (remNode == root)
            return;
        MyTagsTreeNode prnt = (MyTagsTreeNode) TC.getParent();
        SubTree prntNode = prnt.getAssociatedNode();
        prntNode.removeChild(remNode);
        updateTree();
        copyIsPressed = false;
        cutIsPressed = false;
    }//GEN-LAST:event_removeSubTreeButtonActionPerformed

    
    private boolean copyIsPressed = false;
    private SubTree selectedSubTree = null;
    private SubTree selectedSubTreeParent = null;
    private boolean cutIsPressed = false;
    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree selectedNode = TC.getAssociatedNode();
        if (selectedNode == root){
            copyIsPressed = false;
            cutIsPressed = false;
            return;
        }
        selectedSubTree = selectedNode;
        selectedSubTreeParent = ((MyTagsTreeNode)TC.getParent()).getAssociatedNode();
        copyIsPressed = true;
        cutIsPressed = false;
    }//GEN-LAST:event_copyButtonActionPerformed

    private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutButtonActionPerformed
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree selectedNode = TC.getAssociatedNode();
        if (selectedNode == root){
            copyIsPressed = false; 
            cutIsPressed = false;
            return;
        }
        selectedSubTree = selectedNode;
        selectedSubTree = selectedNode;
        selectedSubTreeParent = ((MyTagsTreeNode)TC.getParent()).getAssociatedNode();
        copyIsPressed = false;
        cutIsPressed = true;
    }//GEN-LAST:event_cutButtonActionPerformed

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)
            return;
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree selectedNode = TC.getAssociatedNode();
        SubTree copyOfSelectedSubTree = selectedSubTree.getCopy();
        if (copyIsPressed || cutIsPressed)
            selectedNode.addChild(copyOfSelectedSubTree);
        if (cutIsPressed)
            selectedSubTreeParent.removeChild(selectedSubTree);
        copyIsPressed = false;
        cutIsPressed = false;
        updateTree();
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null){
            pasteButton.setEnabled(false);
            removeSubTreeButton.setEnabled(false);
            removeTagButton.setEnabled(false);
            copyButton.setEnabled(false);
            cutButton.setEnabled(false);
            saveButton.setEnabled(false);
            selectedNodeTextPane.setText("");
            return;
        }
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree selectedNode = TC.getAssociatedNode();
        if (selectedNode == root){
            pasteButton.setEnabled(cutIsPressed || copyIsPressed);
            removeSubTreeButton.setEnabled(false);
            removeTagButton.setEnabled(false);
            copyButton.setEnabled(false);
            cutButton.setEnabled(false);
            selectedNodeTextPane.setText("this is a root");
            saveButton.setEnabled(false);
        }
        else {
            pasteButton.setEnabled(cutIsPressed || copyIsPressed);
            removeSubTreeButton.setEnabled(true);
            removeTagButton.setEnabled(true);
            copyButton.setEnabled(true);
            cutButton.setEnabled(true);
            saveButton.setEnabled(true);
            selectedNodeTextPane.setText("TextContent: "+selectedNode.getTextContent() + "\nAttributes: " + selectedNode.getAttributes());
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree selectedNode = TC.getAssociatedNode();
        try {
            Document xmlDoc = selectedNode.toDocument();
            XMLGenerator.writeDocument(xmlDoc);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private final AttributesTableModel myAtrributeTableModel = new AttributesTableModel();
    private final TagsTableModel myTagsTableModel = new TagsTableModel();
    private final TextContentTableModel myTextContentTableModel = new TextContentTableModel();
    private void attrPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrPlusButtonActionPerformed
        // TODO add your handling code here:
        myAtrributeTableModel.addRow();
    }//GEN-LAST:event_attrPlusButtonActionPerformed

    private void attrMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrMinusButtonActionPerformed
        // TODO add your handling code here:
        int rowIndex = imperativeAttributesTable.getSelectedRow();
        if (rowIndex > -1)
            myAtrributeTableModel.removeRow(rowIndex);
    }//GEN-LAST:event_attrMinusButtonActionPerformed

    private void tagPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagPlusButtonActionPerformed
        // TODO add your handling code here:
        myTagsTableModel.addRow();
    }//GEN-LAST:event_tagPlusButtonActionPerformed

    private void tagMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagMinusButtonActionPerformed
        // TODO add your handling code here:
        int rowIndex = imperativeTagsTable.getSelectedRow();
        if (rowIndex > -1)
            myTagsTableModel.removeRow(rowIndex);
    }//GEN-LAST:event_tagMinusButtonActionPerformed

    private void removeTagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTagButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = jTree1.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        MyTagsTreeNode TC = (MyTagsTreeNode)TP.getLastPathComponent();
        SubTree remNode = TC.getAssociatedNode();
        if (remNode == root)
            return;
        MyTagsTreeNode prnt = (MyTagsTreeNode) TC.getParent();
        SubTree prntNode = prnt.getAssociatedNode();
        prntNode.removeChild(remNode);  
        for (SubTree remNodeChild: remNode.getChildNodes())
            prntNode.addChild(remNodeChild);
        updateTree();
        copyIsPressed = false;
        cutIsPressed = false;
    }//GEN-LAST:event_removeTagButtonActionPerformed

    private void contentPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentPlusButtonActionPerformed
        // TODO add your handling code here:
        myTextContentTableModel.addRow();
    }//GEN-LAST:event_contentPlusButtonActionPerformed

    private void contentMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMinusButtonActionPerformed
        // TODO add your handling code here:
        int rowIndex = textContentTable.getSelectedRow();
        if (rowIndex > -1)
            myTextContentTableModel.removeRow(rowIndex);
    }//GEN-LAST:event_contentMinusButtonActionPerformed
    
    private SubTree root = new SubTree();
    private MyTagsTreeNode jTreeRoot= new MyTagsTreeNode();
    private MyTagsTreeNode getTreeNode(SubTree node){
        ArrayList<SubTree> childNodes = node.getChildNodes();
        MyTagsTreeNode root = new MyTagsTreeNode(node.getTag()); 
        
        root.associateWithNode(node);
        for (SubTree child: childNodes){
            MyTagsTreeNode childNode = getTreeNode(child);
            root.add(childNode);
        }
        return root;
    }
    private void updateTree(){
        jTreeRoot = getTreeNode(root);
        jTree1.setModel(new DefaultTreeModel(jTreeRoot));
        pasteButton.setEnabled(false);
        removeSubTreeButton.setEnabled(false);
        removeTagButton.setEnabled(false);
        copyButton.setEnabled(false);
        cutButton.setEnabled(false);
        saveButton.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFr = new MainFrame();
                mainFr.updateTree();
                mainFr.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attrMinusButton;
    private javax.swing.JButton attrPlusButton;
    private javax.swing.JTextField attributeMaxField;
    private javax.swing.JTextField attributeMinField;
    private javax.swing.JTextField branchMaxField;
    private javax.swing.JTextField branchMinField;
    private javax.swing.JButton contentMinusButton;
    private javax.swing.JButton contentPlusButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton cutButton;
    private javax.swing.JTextField depthMaxField;
    private javax.swing.JTextField depthMinField;
    private javax.swing.JTable imperativeAttributesTable;
    private javax.swing.JTable imperativeTagsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTextField maximalDepthFileld;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton pasteButton;
    private javax.swing.JButton removeSubTreeButton;
    private javax.swing.JButton removeTagButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextPane selectedNodeTextPane;
    private javax.swing.JButton tagMinusButton;
    private javax.swing.JButton tagPlusButton;
    private javax.swing.JTable textContentTable;
    // End of variables declaration//GEN-END:variables
}
